# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - develop

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/assert
  - git submodule init libs/detail
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - cp -r $TRAVIS_BUILD_DIR/* libs/stringify
  - ./bootstrap.sh
  - ./b2 headers

script:
  - TOOLSET=gcc,clang
  - if [ $TRAVIS_OS_NAME == osx ]; then TOOLSET=clang; fi
  - ./b2 libs/stringify toolset=$TOOLSET

notifications:
  email:
    on_success: always

