# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

branches:
  only:
    - master
    - develop
    - /feature\/.*/
    - /release-.*/

matrix:
  include:

    - os: linux
      compiler: gcc
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++1z

    - os: linux
      dist: trusty
      compiler: gcc
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++14

    - os: linux
      dist: trusty
      compiler: gcc
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++1z


#    - os: linux
#      compiler: clang++-3.6
#      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++14
#      addons:
#        apt:
#          packages:
#            - clang-3.6
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#    - os: linux
#      compiler: clang++-3.6
#      env: TOOLSET=clang LLVM_VERSION=3.6.2 COMPILER=clang++-3.6 CXXSTD=c++1z
#      addons:
#        apt:
#          packages:
#            - clang-3.6
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#
#    - os: linux
#      compiler: clang++-3.7
#      env: TOOLSET=clang LLVM_VERSION=3.7.1 COMPILER=clang++-3.7 CXXSTD=c++14
#      addons:
#        apt:
#          packages:
#            - clang-3.7
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#
#    - os: linux
#      compiler: clang++-3.8
#      env: TOOLSET=clang LLVM_VERSION=3.8.0 COMPILER=clang++-3.8 CXXSTD=c++14
#      addons:
#        apt:
#          packages:
#            - clang-3.8
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#
#    - os: linux
#      compiler: clang++-3.8
#      env: TOOLSET=clang LLVM_VERSION=3.8.0 COMPILER=clang++-3.8 CXXSTD=c++1z
#      addons:
#        apt:
#          packages:
#            - clang-3.8
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#
#
#    - os: linux
#      compiler: clang++-3.9
#      env: TOOLSET=clang LLVM_VERSION=3.9.0 COMPILER=clang++-3.9 CXXSTD=c++14
#      addons:
#        apt:
#          packages:
#            - clang-3.9
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.9
#
#    - os: linux
#      compiler: clang++-3.9
#      env: TOOLSET=clang LLVM_VERSION=3.9.0 COMPILER=clang++-3.9 CXXSTD=c++1z
#      addons:
#        apt:
#          packages:
#            - clang-3.9
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.9
#
#    - os: linux
#      compiler: clang++-4.0
#      env: TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=c++14
#      addons:
#        apt:
#          packages:
#            - clang-4.0
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-4.0
#
#    - os: linux
#      compiler: clang++-4.0
#      env: TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=c++1z
#      addons:
#        apt:
#          packages:
#            - clang-4.0
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-4.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z


install:
  - cd ..
  - git clone -b develop https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/assert
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/detail
  - git submodule init libs/utility
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - mkdir -p libs/stringify
  - cp -r $TRAVIS_BUILD_DIR/* libs/stringify
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - ./b2 libs/stringify toolset=$TOOLSET

notifications:
  email:
    on_success: always

