dist: xenial
language: cpp

env:

#install:
#  - source ci/travis/install.sh
#  - cd $BOOST_ROOT && ./b2 headers

addons:
  apt:
    packages:
      - binutils-gold
      - gdb
      - libc6-dbg

branches:
  only:
    - master
    - develop
    - /pr-.*/
    - /rc-.*/
    - /bugfix-.*/
    - /hotfix-.*/
    - /feature-.*/
    - /optimization-.*/
    - /refactoring-.*/
    - /redesign-.*/
    - /task-.*/

#
# Default toolsets in Ubuntu
#
#       trusty xenial bionic
#        14.04  16.04  18.04
#       ------ ------ ------
# clang    3.4    3.8    6.0
#   gcc  4.8.2  5.3.1  7.3.0
#

anchors:
  clang-38: &clang-38 { apt: { packages: [ "clang-3.8",
                                           "libstdc++-6-dev" ], sources: [ "llvm-toolchain-xenial-3.8",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-4:  &clang-4  { apt: { packages: [ "clang-4.0",
                                           "libstdc++-6-dev" ], sources: [ "llvm-toolchain-xenial-4.0",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-5:  &clang-5  { apt: { packages: [ "clang-5.0",
                                           "libstdc++-7-dev" ], sources: [ "llvm-toolchain-xenial-5.0",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-6:  &clang-6  { apt: { packages: [ "clang-6.0",
                                           "libc6-dbg",
                                           "libc++-dev",
                                           "libstdc++-8-dev" ], sources: [ "llvm-toolchain-xenial-6.0",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-7:  &clang-7  { apt: { packages: [ "clang-7",
                                           "libc6-dbg",
                                           "libc++-dev",
                                           "libstdc++-8-dev" ], sources: [ "llvm-toolchain-xenial-7",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-8:  &clang-8  { apt: { packages: [ "clang-8",
                                           "libc6-dbg",
                                           "libc++-dev",
                                           "libstdc++-8-dev" ], sources: [ "llvm-toolchain-xenial-8",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  gcc-6:    &gcc-6    { apt: { packages: [ "g++-6"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }
  gcc-7:    &gcc-7    { apt: { packages: [ "g++-7"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }
  gcc-8:    &gcc-8    { apt: { packages: [ "g++-8"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }
  gcc-9:    &gcc-9    { apt: { packages: [ "g++-9"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }

jobs:
  allow_failures:
    - env:
      - COPY="all the environment settings from your job"

  include:
    - { os: "linux", env: [ "CXX=clang++-3.8", "CXX_STANDARD=14", CONFIG=Debug    ], addons: *clang-38 }
    - { os: "linux", env: [ "CXX=clang++-8", "CXX_STANDARD=17", CONFIG=Debug    ], addons: *clang-8  }
    - { os: "linux", env: [ "CXX=g++-6", "CXX_STANDARD=14", CONFIG=Debug    ], addons: *gcc-6 }
    - { os: "linux", env: [ "CXX=g++-6", "CXX_STANDARD=14", CONFIG=Release  ], addons: *gcc-6 }
    - { os: "linux", env: [ "CXX=g++-7", "CXX_STANDARD=14", CONFIG=Debug    ], addons: *gcc-7 }
    - { os: "linux", env: [ "CXX=g++-7", "CXX_STANDARD=17", CONFIG=Debug    ], addons: *gcc-7 }
    - { os: "linux", env: [ "CXX=g++-8", "CXX_STANDARD=14", CONFIG=Debug    ], addons: *gcc-8 }
    - { os: "linux", env: [ "CXX=g++-8", "CXX_STANDARD=20", CONFIG=Debug    ], addons: *gcc-8 }
    - { os: "linux", env: [ "CXX=g++-8", "CXX_STANDARD=20", CONFIG=Release  ], addons: *gcc-8 }
    - { os: "linux", env: [ "CXX=g++-9", "CXX_STANDARD=17", CONFIG=Debug    ], addons: *gcc-9 }
    - { os: "linux", env: [ "CXX=g++-9", "CXX_STANDARD=20", CONFIG=Debug    ], addons: *gcc-9 }
    - { os: "linux", env: [ "CXX=g++-9", "CXX_STANDARD=20", CONFIG=Release  ], addons: *gcc-9 }
    - os: linux
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libperlio-gzip-perl libjson-perl locales-all
      env: [ "COMMENT=codecov.io", "CC=gcc-7", "CXX=g++-7", "CXX_STANDARD=14", "GCOV=gcov-7" ]
      addons: *gcc-7
      script:
        - pushd /tmp && git clone https://github.com/linux-test-project/lcov.git && export PATH=/tmp/lcov/bin:$PATH && which lcov && lcov --version && popd
        - ci/travis/codecov_build.sh
    - os: linux1
      env: [ "COMMENT=ubsan", "CC=gcc-8", "CXX=g++-8", "CXX_STANDARD=14", CONFIG=Debug ]
      addons: *gcc-8
      script:
        - ci/travis/ubsan_build.sh

notifications:
  email:
    false

script:
  - ./ci/travis/build.sh
