# Copyright 2016, 2017 Peter Dimov
# Copyright (C) 2017, 2018 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

# This file is a customization of the template located in
# https://github.com/boostorg/boost-ci

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/
    - /release-.*/

environment:
  matrix:
    - FLAVOR: Visual Studio 2017 C++2a Strict
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64
      CXXFLAGS: cxxflags=-permissive-
      CXXSTD: latest # 2a

    - FLAVOR: Visual Studio 2017 C++17
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 17

    - FLAVOR: Visual Studio 2017 C++14 (Default)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      B2_ADDRESS_MODEL: address-model=64,32

    - FLAVOR: cygwin (64-bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ADDPATH: C:\cygwin64\bin;
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 14,17
      # https://github.com/boostorg/test/issues/144
      DEFINES: define=_POSIX_C_SOURCE=200112L define=__USE_ISOC99
      THREADING: threadapi=pthread
      TOOLSET: gcc

    - FLAVOR: mingw64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64
      B2_ADDRESS_MODEL: address-model=64
      CXXSTD: 14,17
      DEFINES: define=__USE_ISOC99
      SCRIPT: ci\appveyor\mingw.bat


install:
  - set SELF=stringify
  - git clone https://github.com/boostorg/boost-ci.git C:\boost-ci
  - xcopy /s /e /q /i C:\boost-ci\ci .\ci
  - cd ..
  - git clone -b develop https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/headers
  - git submodule init libs/assert
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/detail
  - git submodule init libs/hana
  - git submodule init libs/optional
  - git submodule init libs/utility         # boost::string_view
  - git submodule init libs/exception       # required by boost::string_view
  - git submodule init libs/throw_exception # required by boost::string_view
  - git submodule init libs/container_hash  # required by boost::string_view
  - git submodule init tools/boost_install
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - xcopy /s /e /q /i %APPVEYOR_BUILD_FOLDER% libs\stringify\
  - bootstrap
  - b2 headers

build: off

test_script:
  - set SELF=stringify
  - PATH=%ADDPATH%%PATH%
  # The definition of TOOLCXX omits CXXSTD= if it was not defined above
  - IF NOT DEFINED CXXSTD (SET TOOLCXX=toolset=%TOOLSET%) ELSE (SET TOOLCXX=toolset=%TOOLSET% cxxstd=%CXXSTD%)
  # Echo the complete build command to the build log
  - IF NOT DEFINED SCRIPT                         (ECHO b2 libs/%SELF:\=/% %TOOLCXX% %CXXFLAGS% %DEFINES% %THREADING% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)
  # Now go build...
  - IF DEFINED SCRIPT (call libs\%SELF%\%SCRIPT%) ELSE (b2 libs/%SELF:\=/% %TOOLCXX% %CXXFLAGS% %DEFINES% %THREADING% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3)
