# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - develop

install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/assert
  - git submodule init libs/detail
  - git submodule init tools/build
  - git submodule init tools/inspect
  - git submodule update
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\stringify
  - bootstrap
  - b2 headers

build: off

test_script:
  - cd libs/stringify
  - mkdir cmake_build
  - cd cmake_build
  - cmake -G "Visual Studio 15 2017" ..
  - cmake --build .
  - ctest -C Debug

#  - b2 libs/smart_ptr/test toolset=msvc-15.0
